version: "3.8"

services:
  backend:
    build:
      context: ./MoviePage
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./Moviepage_Frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
